import React, { Component } from 'react';
import {AppRegistry} from 'react-native';
///var test = require('./tab');
//var test = require('./Pet');
var test = require('./battle');
//var test = require('./SampleComponent');
//var test = require('./NavBox');
//var test = require('./MapExample');
//var test = require('./apptest');
AppRegistry.registerComponent('test', () => test);
