import React, { Component } from 'react';
import {AppRegistry} from 'react-native';
var test = require('./tab');
//var test = require('./Pet');
//var test = require('./battle');
//var test = require('./SampleComponent');
//var test = require('./NavBox');
//var test = require('./MapExample');
//var test = require('./SensorTest');
//var test = require('./NavPet');
//var test = require('./object');
AppRegistry.registerComponent('test', () => test);
