import React, { Component } from 'react';
import {AppRegistry} from 'react-native';
//var test = require('./tab');
//var test = require('./battle');
//var test = require('./SampleComponent');
//var test = require('./NavBox');
//var test = require('./MapExample');
//var test = require('./SensorTest');
//var test = require('./NavPet');
var test = require('./object');
//var test = require('./NavPet');
//var test = require('./SpeechbubbleTest');
//var test = require('./FetchTest');
//var test = require('./NewMap');
//var test = require('./swiper');
AppRegistry.registerComponent('test', () => test);
